# default configuration
baseURL = "https://frenchtechvietnam.com"
languageCode = "en-us"
summaryLength = "10"
theme = "kross"
title = "French Tech Vietnam HDH"

# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"


# js plugin
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"


# menu
[[menu.main]]
URL = "about"
name = "About"
weight = 1

[[menu.main]]
URL = "news"
name = "News"
weight = 2

[[menu.main]]
URL = "https://job.ftnext40.com/jobs"
name = "Jobboard"
weight = 3

[[menu.main]]
URL = "https://job.ftnext40.com/jobs/new"
name = "Post a Job"
weight = 4

[[menu.main]]
URL = "contact"
name = "Contact"
weight = 5


# default parameters
[params]
home = "Home"
logo = "/uploads/logo/logo_medium_small.png"
# theme color
#theme_color = "#41228e"
theme_color = "#0D0040"

# contact info
phone = ""
email = "contact@frenchtechvietnam.com"
address = "Made with love ♥ in Saigon, Vietnam"
# meta description
author = "La French Tech Viet HDH"
description = "This is meta description"
# google analytics
google_analytics_id = "G-6K0H46Y40V" # Your ID
# copyright
copyright = "Copyright &copy; 2020 French Tech Vietnam HDH"

# preloader
[params.preloader]
enable = true
preloader = "images/line-preloader.gif" # use png, jpg, svg or gif format

# contact
[params.contact]
enable = true
form_action = "https://formspree.io/myybgaab" # contact form works with : https://formspree.io

# google map
[params.map]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=&#038;types=(cities)&#038;libraries=places&#038;language=en"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"

# social site
[[params.social]]
icon = "ti-facebook"
URL = "https://www.facebook.com/laFrenchTechViet"

[[params.social]]
icon = "ti-linkedin"
URL = "https://www.linkedin.com/company/frenchtechvietnam/"

[[params.social]]
icon = "ti-twitter-alt"
URL = "https://twitter.com/FrenchTechViet"
